"use client";
import ShowApplicants from "@/components/dashboard/ShowApplicants";
export default function Page() {
   type applicantDataType = {
      profileId?: string;
      profile?: string;
      resume?: string;
      username?: string;
      bio?: string;
      education?: string;
      experience?: string;
      company?: string;
      time?: number;
      yearsOrMonth?: string;
      phone?: number;
      linkedin?: string;
      gitHub?: string;
   };

   const applicants: applicantDataType[] = [
      {
         profileId: "12345",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Shreeram",
         bio: "This is my bio hjghdgdsb gdggdsgds ghgdggd  hjghdgdsb gdggdsgds ghgdggd hjghdgdsb gdggdsgds ghgdggd hjghdgdsb gdggdsgds ghgdggd hjghdgdsb gdggdsgds ghgdggd hjghdgdsb gdggdsgds ghgdggd hjghdgdsb gdggdsgds ghgdggd",
         education: "BCA",
         experience: "yes",
         company: "Tikanga pvt ltd",
         time: 1,
         yearsOrMonth: "months",
         phone: 1234567890,
         linkedin: "https://linkedin.com/in/shreeram",
         gitHub: "https://github.com/shreeram",
      },
      {
         profileId: "12346",
         profile: "ggdg",
         resume: "ghsghs",
         username: "John Doe",
         bio: "Experienced software engineer with a passion for frontend development.",
         education: "Bachelor's in Computer Science",
         experience: "5 years",
         company: "Tech Solutions Inc.",
         time: 40,
         yearsOrMonth: "months",
         phone: 9876543210,
         linkedin: "https://linkedin.com/in/johndoe",
         gitHub: "https://github.com/johndoe",
      },
      {
         profileId: "12347",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Jane Smith",
         bio: "Aspiring web developer with a focus on UX/UI design.",
         education: "Master's in Information Technology",
         experience: "2 years",
         company: "Digital Innovations Ltd.",
         time: 30,
         yearsOrMonth: "years",
         phone: 5551234567,
         linkedin: "https://linkedin.com/in/janesmith",
         gitHub: "https://github.com/janesmith",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
      {
         profileId: "12348",
         profile: "ggdg",
         resume: "ghsghs",
         username: "Michael Johnson",
         bio: "Passionate about backend systems and scalability.",
         education: "Bachelor's in Computer Engineering",
         experience: "8 years",
         company: "Backend Solutions Corp.",
         time: 50,
         yearsOrMonth: "years",
         phone: 9998765432,
         linkedin: "https://linkedin.com/in/michaeljohnson",
         gitHub: "https://github.com/michaeljohnson",
      },
   ];
   return <ShowApplicants applicants={applicants} />;
}
